baseURL = "/"
languageCode = "en-us"
title = "Hui Zhou"
description = "Welcome to Hui's personal website!"
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    name = "Hui Zhou"
    role = "Professor of Artificial Intelligence"
    organizations = [ { name = "Stanford University", url = "" } ]
    description = "I am a Ph.D. Candidate in the Department of Political Science at the University of Houston. My research fields include public policy and comparative politics. Prior to attending graduate school, I earned a B.A. in Economics (2014) and an M.A. in Management (2016) in China. As a Ph.D. Candidate, I expect to graduate in the May of 2022. My research interests center on  the nexus between political institutions and governance. I am particularly interested in how political institutions and economic factors shape bureaucratic accountability, government responsiveness, and policy outcomes in authoritarian contexts. My studies on China’s health policy and judicial reform have occurred at Journal of Contemporary China, Social Science and Medicine and International Journal of Legal Medicine. Besides, I coauthored a book chapter on China’s social policy and social equity."
    gravatar = false  # Get your avatar from Gravatar.com? (true/false)
    #avatar = "Hui-Zhou.jpg.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
    logo = "Headshot_Circle.png"
    email = "test@example.org"
    address = "Building 1 Room 1, Stanford University, California, 90210, USA"
    office_hours = "Monday 10:00 to 13:00 or email for appointment"
    phone = "888 888 88 88"
    accent = "#386890" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Ovo" # should match the name on Google Fonts! (default is Mina) options: Lateef, Ovo
    #fontsize = 2
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/About/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/Research/"
    name = "Research"
    weight = 3

[[menu.main]]
    url = "/Teaching/"
    name = "Teaching"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:huizhou68@gmail.com"
    name = "far fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/huizhou68"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/hzhou21"
    name = "fab fa-twitter"
    weight = 3
  
